### ISSUE TITLE
Implementar Login via Github e Twitter

### ISSUE THREAD

**Issue by J-Cunha** [J-Cunha/cryptocoinsmap#8]
Usando Omniauth, Implementar login via twitter e github.

**Comment by neilrioszamora** [comment]
https://github.com/J-Cunha/cryptocoinsmap/pull/12

**Comment by neilrioszamora** [comment]
https://github.com/J-Cunha/cryptocoinsmap/pull/13

**Comment by neilrioszamora** [comment]
Here's the merged one https://github.com/J-Cunha/cryptocoinsmap/pull/14

**Comment by J-Cunha** [comment]
Good Work Neil, you told that you could make and you have done.
Thanks!
